version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - type: bind
        source: ./app
        target: /app
      - dev-static-data:/vol/web
      - ws-static:/tmp
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
      - AWS_CLOUDFRONT_KEY_ID
      - AWS_CLOUDFRONT_KEY
      - AWS_CLOUDFRONT_DOMAIN
      - DEBUG=1
      - DEV_ENV  
      - TZ='GMT+8'
      - PGTZ='GMT+8'
    depends_on:
      - db
      - cache
  worker:
    build:
      context: .
      args:
        - DEV=true
    command: celery -A app worker --loglevel=info
    volumes:
      - dev-static-data:/vol/worker
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
      - TZ='GMT+8'
      - PGTZ='GMT+8'
    depends_on:
      - db
      - cache
  beat:
    image: as2229181/cooknetwork:worker_v1.0
    build:
      context: .
      args:
        - DEV=true
        - SERVICE_TYPE=beat
    command: celery -A app beat -l info
    volumes:
      - dev-static-data:/vol/beat
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
      - TZ='GMT+8'
      - PGTZ='GMT+8'
    depends_on:
      - db
      - cache
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - TZ='GMT+8'
      - PGTZ='GMT+8'
  cache:
    image: redis:7.2.1-alpine
    environment:
      - TZ='GMT+8'
      - PGTZ='GMT+8'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/vol/redis

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
      - 443:8443
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/www/certbot:/var/www/certbot
      - ./var/log/letsencrypt:/var/log/letsencrypt
      - ./var/lib/letsencrypt:/var/lib/letsencrypt
      - dev-static-data:/vol/web/static
      - ws-static:/tmp
    environment:
      - TZ='GMT+8'
      - PGTZ='GMT+8'
volumes:
  dev-db-data:
  dev-static-data:
  redis-data:
  ws-static:
