version: '3.9'

services:
  app:
    image: as2229181/cooknetwork:app_v1.0
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
      - TZ='GMT+8'
      - PGTZ='GMT+8'      
    depends_on:
      - db
      - cache
  worker:
    image: as2229181/cooknetwork:worker_v1.0
    build:
      context: .
      args:
        - DEV=true
    command: celery -A app worker --loglevel=info
    volumes:
      - dev-static-data:/vol/worker
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
      - TZ='GMT+8'
      - PGTZ='GMT+8'
    depends_on:
      - db
      - cache
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - TZ='GMT+8'
      - PGTZ='GMT+8'
  cache:
    image: redis:7.2.1-alpine

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - dev-static-data:/vol/static
    environment:
      - TZ='GMT+8'
      - PGTZ='GMT+8'    
volumes:
  dev-db-data:
  dev-static-data:
