version: '3.9'

services:
  app:
    image: as2229181/cooknetwork:app_v1.0
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db
      - cache
  worker:
    image: as2229181/cooknetwork:worker_v1.0
    build:
      context: .
      args:
        - DEV=true
    command: celery -A app worker --loglevel=info 
    volumes:
      - dev-static-data:/vol/worker
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db
      - cache
  beat:
    image: as2229181/cooknetwork:worker_v1.0
    build:
      context: .
      args:
        - DEV=true
    command:  /bin/sh -c "chmod 644 /home/celery/var/run/celerybeat-schedule && exec your_main_command"
    volumes:
      - dev-static-data:/vol/beat
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db
      - cache    
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  cache:
    image: redis:7.2.1-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/vol/redis

volumes:
  dev-db-data:
  dev-static-data:
  redis-data:
