# Generated by Django 3.2.22 on 2023-10-20 02:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimageupload',
            name='uuid',
            field=models.CharField(default=core.models.generate_prefixed_uuid, editable=False, max_length=50, unique=True),
        ),
    ]
