# Generated by Django 3.2.22 on 2023-10-22 10:23

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimageupload_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='photo',
        ),
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=core.models.upload_image_file_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('main', 'Main'), ('sub_2', 'Sub_2'), ('sub_3', 'Sub_3')], default='main', max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.recipe')),
            ],
        ),
    ]
