# Generated by Django 3.2.22 on 2023-10-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231022_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='save',
            new_name='save_count',
        ),
    ]
