# Generated by Django 3.2.22 on 2023-10-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_save_recipe_save_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='save',
            new_name='save_count',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='save',
            new_name='save_count',
        ),
    ]
