# Generated by Django 3.2.22 on 2023-10-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_user', max_length=255, unique=True),
        ),
    ]
