# Generated by Django 3.2.22 on 2023-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231025_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
