# Generated by Django 3.2.25 on 2024-03-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240306_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverimage',
            name='category',
        ),
    ]
