# Generated by Django 3.2.25 on 2024-03-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_coverimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverimage', to='core.recipe'),
        ),
    ]
