# Generated by Django 3.2.23 on 2023-11-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_like_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipe', to='core.recipe'),
        ),
    ]
