# Generated by Django 3.2.23 on 2023-11-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomment',
            name='crated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='rating',
            field=models.IntegerField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='1', help_text='rating form 1 to 5', max_length=1),
        ),
    ]
