# Generated by Django 3.2.23 on 2023-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20231114_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='rating',
            field=models.IntegerField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='1', help_text='rating form 1 to 5'),
        ),
    ]
