# Generated by Django 3.2.23 on 2023-11-14 08:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_recipecomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='Photo',
            field=models.ImageField(null=True, upload_to=core.models.comment_image_file_path),
        ),
    ]
