# Generated by Django 3.2.23 on 2023-11-15 14:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recipe_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.comment_image_file_path),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='rating',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default='1', help_text='rating form 1 to 5'),
        ),
    ]
