# Generated by Django 3.2.23 on 2023-11-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_recipe_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comment', to='core.recipe'),
        ),
    ]
